webapp/models.py
from ISA import db

from datetime import datetime

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

app.py
from flask import Flask, render_template,redirect

app = Flask(__name__)


@app.route('/')
@app.route('/home')
def index():
    user = {'username' : 'Miguel'}
    posts = [
        {
            'author' : {'username' : 'John'},
            'body': 'Beautiful day in Portland!'
        },
        {
            'author': {'username': 'Susan'},
            'body': 'The avengers movie was so cool!'
        }
    ]
    return render_template('index.html', title='Home', user=user, posts=posts)

@app.route('/index.html')
def root():
    return redirect('/')

@app.route('/about')
def about():
    return render_template('about.html')

if __name__ == '__main__':
    app.run()

app/routes.py
from flask import Flask, render_template, flash, redirect, url_for, Blueprint
from app.forms import LoginForm

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def index():
    user = {'username' : 'Miguel'}
    posts = [
        {
            'author' : {'username' : 'John'},
            'body': 'Beautiful day in Portland!'
        },
        {
            'author': {'username': 'Susan'},
            'body': 'The avengers movie was so cool!'
        }
    ]
    return render_template('index.html', title='Home', user=user, posts=posts)

@main.route('/index')
def root():
    return redirect(url_for('main.index'))

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        flash('Login requested for user {}, remember_me={}'.format(
            form.username.data, form.remember_me.data))
        return redirect(url_for('index'))
    return render_template('login.html', title='Sign In', form=form)

webapp/__init__.py
from webapp import routes
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from webapp.routes import main
import config

'''
app = Flask(__name__)
app.config.from_object(config)
from webapp.routes import main
app.register_blueprint(main)



db = SQLAlchemy(app)
migrate = Migrate(app, db)
'''

webapp/routes.py
from flask import Flask, render_template, flash, redirect, url_for, Blueprint
from webapp.forms import LoginForm

main = Blueprint('main', __name__)
username = ""


@main.route('/')
@main.route('/home')
def index():
    print(username)
    print(username)
    return render_template('index.html', title='Home', user=username)


@main.route('/index')
def root():
    return redirect(url_for('main.index'))


@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/test')
def test():
    from ISA import db
    from webapp.models import User
    #db.create_all()
    #u = User(username="Cucklord", email="harryn@gmail.com")
    #db.session.add(u)
    #db.session.commit()

    users = User.query.all()
    print(users)
    return render_template('test.html', user=users)


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    global username
    if form.validate_on_submit():
        flash('Login requested for user {}, remember_me={}'.format(
            form.username.data, form.remember_me.data))
        username = form.username.data
        return redirect(url_for('main.index'))
    return render_template('login.html', title='Sign In', form=form)


@main.route('/training')
def training():
    email_slots = [{"slot": "slot"+str(x),
                    "buttonid":"emailBtn"+str(x),
                    "name":"Email "+str(x),
                    "iframeid":"email"+str(x),
                    "src":"email/testemail"+str(x),
                    "iframename":"iframe"+str(x)
                    } for x in range(1, 10)]

    answer_slots = [{"slot": "slot" + str(y),
                     "answerButtons":"answerButtons" + str(y),
                     "answerid":"answerBtn:"+str(y),
                     "answerConfirm":"answerConfirm"+str(y),
                     "name":"Is Email "+str(y)+" a phishing email?" } for y in range(1, 10)]
    return render_template('training.html', emails=email_slots, answers=answer_slots)



@main.route('/email/<arg1>', methods=['GET'])
def testemail(arg1):



    return render_template('email/{0}.html'.format(arg1))

templates/about.html
{% extends "base.html" %}
{% block content %}

<div id = "aboutoverlay"></div>
    <div id ="subheading"><h1>Phishing education made easy</h1></div>
    <div id ="abouttext"><p>Is this a phish is an online training tool that aims to educate on how to prevent yourself from becoming the victim of a phishing
attack. The method of this is by providing sample legitimate and illegitimate emails and allowing the user to identify which ones
they think are legitimate or illegitimate. The tool also gives educational hints and tests to check your progress.</p></div>
    <div id ="subheading2"><h1>Find out more</h1></div>
    <div id = "aboutsignup">
        <a href="{{ url_for('main.login') }}">
    <button id = "signupbutton" class="buttonStyle">Sign Up</button>
        </a>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% if title %}
        <title>{{ title }} - ISA Training</title>
        {% else %}
        <title>ISA Training</title>
        {% endif %}
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <script src="/static/js/lessonControl.js"></script>
        <script src="/static/js/iframeVisibility.js"></script>
        <script src="/static/js/answerControl.js"></script>
    </head>

    <body>
    <div id ="wrapper">

            <div class = "container">
                <div class ="topnav">
            <a href="{{ url_for('main.index') }}">Home</a>
            <a href="{{ url_for('main.about') }}">About</a>
            <a href="{{ url_for('main.training') }}">Training</a>
            <a href="{{ url_for('main.login') }}">Sign In</a>
                </div>
            </div>
        {% block content %}{% endblock %}
    </div>
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class = "intro">
        <p>Welcome to is this a phish, the online training tool for improving
            awareness about phishing emails and how to avoid and identify them.
            Protect your data with education.
        </p>
    </div>
    <div class = "homesignin">
        <a href="{{ url_for('main.login') }}">
    <button id = "signinbutton" class="buttonStyle">Sign In</button>
    <button id = "signupbutton" class="buttonStyle">Sign Up</button>
        </a>
    </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
        <h1>ISA Training</h1>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block content %}
    <h1>Hi, {{ user }}!</h1>
    {% for user in users %}
    <div><p>{{ user.username }} says: <b>{{ user.email }}</b></p></div>
    {% endfor %}
{% endblock %}

templates/training.html
{% extends "base.html" %}
{% block content %}
    <div class="trainingScroll">
        <div id="app">
            <div class="inboxpanel">
                <button id="inboxbtn" class="inboxBtn">Inbox</button>
                <button id="realemail" class="inboxBtn">Legitimate Emails</button>
                <button id="fakeemail" class="inboxBtn">Phishing Emails</button>
            </div>
            <div class="emails">

                {% for email in emails %}
                    <div class= {{ email['slot'] }}>
                        <button id={{ email['buttonid'] }} class="emailBtn"
                                onclick="toShow(this.id)"> {{ email['name'] }} </button>
                        <iframe style="display:none;" class="iframes" id=emailFrame
                                src={{ email['src'] }} name={{ email['iframename'] }}></iframe>
                    </div>
                {% endfor %}

            </div>
            <div class="lesson">
                <div class="lessonTitle"><p>Lesson</p></div>
                <div class="lessonTextBox">
                    <p id="lessonText">Welcome to the lesson introduction, in this space a lesson will appear giving you
                        instructions on what you must do. When are you are ready to get started, please click next
                        lesson below.</p>
                </div>
                <div class="lessonBtn">
                    <button id="previous" onclick='prevLesson()' class="lessonBtn">Previous Lesson</button>
                    <button id="nextLesson" onclick='nextLesson()' class="lessonBtn">Next Lesson</button>
                </div>
                <div class="answerTitle"><p>Answers</div>
                <div class="answerBox">
                    {% for answer in answers %}
                        <div class= {{ answer['slot'] }}>
                            <p id="answerText"> {{ answer['name'] }}</p>
                            <p id= {{ answer['answerConfirm'] }}></p>
                            <div id={{ answer['answerButtons'] }} class="answerButtons">
                                <button id={{ answer['answerid'] }} class="answerBtn"
                                        onclick='checkAnswer(emailid=this.id, answer=1)'> Yes
                                </button>
                                <button id={{ answer['answerid'] }} class="answerBtn"
                                        onclick='checkAnswer(emailid=this.id, answer=0)'> No
                                </button>
                            </div>
                        </div>
                    {% endfor %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}